name: dotfiles CI

on:
  push:
    branches: [ master ]
  pull_request:
    types: [ opened, synchronize, reopened, edited ]
  schedule:
    - cron: '0 3 * * 6'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-linux:
    name: Install on Linux locally
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Run install script
      run: ./install.sh

    - name: Ensure zsh works
      run: exec zsh

  build-linux-docker:
    name: Install on Linux in Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build . -t dotfiles

      - name: Run Dockerfile
        run: docker run dotfiles

  build-macos:
    name: Install on macOS
    runs-on: macos-latest

    steps:
    - name: Unlink preinstalled node
      run: brew unlink node@12

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Run install script
      run: ./install.sh

    - name: Ensure zsh works
      run: exec zsh
