name: dotfiles CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: apt-get update && apt-get install curl git make sudo zsh -y

    - name: Create non-root user
      run: useradd -m -s /bin/bash actions && echo 'actions ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers;

    - name: Switch to user
      run: su - actions && cd ~

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Run install script
      run: ./install.sh
